version: '3'
services:
  cert:
    build: ../mkcert2
    container_name: mkcertiiii2
    depends_on:
      - app
    volumes:
      - ./flask_demo:/opt/mkcert/data
      - ./flask_demo/rootCA:/cem/.local/share/mkcert

  app:
    build: .
    ports:
      - "5000:5000"
    container_name: py_webauthn
    volumes:
      - ./webauthn:/app/webauthn:ro
      - ./flask_demo:/app/flask_demo:ro
