# Folgender Code stammt vom Unternehmen Duo Security und wurde unter dem Link https://github.com/duo-labs/py_webauthn von GitHub heruntergeladen. 
# Einige Abschnitte Stammen vom Autor der Arbeit "Implementierung und Einsatz des WebAuthn-Standard".
# Um welche Abschnitte es sich dabei handelt, ist der genannten Arbeit zu entnehmen.

version: '3'
services:
  cert:
    build: ../mkcert2
    container_name: mkcertiiii2
    depends_on:
      - app
    volumes:
      - ./flask_demo:/opt/mkcert/data
      - ./flask_demo/rootCA:/cem/.local/share/mkcert

  app:
    build: .
    ports:
      - "5000:5000"
    container_name: py_webauthn
    volumes:
      - ./webauthn:/app/webauthn:ro
      - ./flask_demo:/app/flask_demo:ro
